### PR TITLE
Small fixes to seemingly changed function signatures

### PR DESCRIPTION
**Pull request by t3hmrman**
Current master branch of node-pocketsphinx does not build correctly with the following software versions:
node v0.10.25
npm 2.2.0
node-gyp v0.10.9

Seems like some of the function signatures have changed, two build errors were caused by seemingly now-unneeded arguments.

This pull request should probably be closely reviewed to ensure that semantics/functionality is not broken -- these changes are just to get it to build, have not been thoroughly tested.

### CODE REVIEW

**Comment by nshmyrev** [comment]
There is actually more advanced

https://github.com/SPARTAN563/node-pocketsphinx

You might want to try it instead

**Comment by nshmyrev** [comment]
I merged it into our repo and updated uttid-related api

**Comment by t3hmrman** [comment]
hey @nshmyrev, sorry for the incomplete pull request, glad you were able to reconcile the changes!

Yeah, I think I still have a ways to go before it will work on node-webkit, going to checkout @SPARTAN563's repo

**Comment by SPARTAN563** [comment]
Just to let you guys know, my repo is based on the latest source release of pocketsphinx - so you'll have issues making use of it using the current binary release (0.8). They made a number of changes to the API and the way the engine handles switching configurations between 0.8 and the current master code.

**Comment by t3hmrman** [comment]
Hey @SPARTAN563 ,

Oops, I didn't realize that, actually just sent a PR with the same changes outlined here -- since I'm still using node 10.x I'm stuck on nw 0.8 -- will close the PR

**Pull request closed without merging**
