### PR TITLE
Use NaN in order to make this compatible with newer version of node

### PR DESCRIPTION
**Pull request by Prior99**
Please note that as of the different getter-setter-api of NaN you will now have to use:

    sphinx.search = "..."

instead of

    sphinx.search("...")

### CODE REVIEW

**Comment by Prior99** [comment]
@cmusphinx could this be merged an published to npmjs or at least be commented at for why not being merged?

**Comment by nshmyrev** [comment]
Thank you for the contribution, I will merge it in few days. I just need to set node and test it myself. There is also an issue with pushing it to npm, I believe I don't have permissions for that, need to figure out how to get ownership over the repository.

**Comment by Prior99** [comment]
Thank you.

**Comment by Prior99** [comment]
3 weeks later this is sadly still not merged.

**Comment by nshmyrev** [comment]
Updated to latest node

**Comment by nshmyrev** [comment]
Thank you very much for contribution!

**Pull request closed without merging**
